# -*- coding: utf-8 -*-
"""NitrateDataCleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1orrCwioasV_yfqjmbVmLMyUIJ3TLQoKF
"""

import pandas as pd
ic_nitrates = pd.read_csv("nitrates_master.csv") # from excel datalink

# minor preprocessing
ic_nitrates.columns = ic_nitrates.columns.str.strip()
ic_nitrates['timestamp'] = pd.to_datetime(ic_nitrates['timestamp'], utc=True)
ic_nitrates = ic_nitrates.replace('No Data', pd.NA)
ic_nitrates = ic_nitrates.replace('Pt Created', pd.NA)
ic_nitrates = ic_nitrates.replace('Bad', pd.NA)

for cols in ic_nitrates.columns:
    if ic_nitrates[cols].dtype == 'object':
        ic_nitrates[cols] = pd.to_numeric(ic_nitrates[cols], errors='coerce')

ic_nitrates['WCP_00_TT_091'] = ic_nitrates['WCP_00_TT_091'].fillna(method='ffill')
ic_nitrates['WP_WC_Nitrate_River'] = ic_nitrates['WP_WC_Nitrate_River'].fillna(method='ffill')

# conversion to time-series-like dataframe
nitrates_ts = (
    ic_nitrates
    .set_index("timestamp")
    .sort_index()
)

ic_weather = pd.read_csv("ic_weather.csv") # Ariadna's data
ic_weather = ic_weather[:-6]

prcp = ic_weather[['PRCP']]
prcp['timestamp'] = pd.to_datetime(ic_weather['DATE'], utc=True)

# Reindex precip onto the master index, then ffill
prcp = prcp.set_index('timestamp')
master_index = nitrates_ts.index
prcp = prcp.reindex(master_index, method='ffill')

nitrates_ts = nitrates_ts.join(prcp)

cols = ['CoralvilleReservoir_USACE_Level',
       'CoralvilleReservoir_USACE_Outflow',
       'CoralvilleReservoir_USACE_Inflow_Davg',
       'IowaCityAirport_Weather_Temperature',
       'IowaCityAirport_Weather_RelativeHumidity',
       'IowaCityAirport_Weather_Precipitation_Htot',
        'WCP_00_MT_091',
        'WCP_00_LS_091']
nitrates_ts = nitrates_ts.drop(cols, axis=1)

nitrates_ts.to_csv('nitrates_ts.csv')