# -*- coding: utf-8 -*-
"""synoptic_api.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sW-_mMZNq8fdo3ZCur-nT1HE0bVfY2y0
"""

import requests
import pandas as pd
from datetime import datetime, timedelta

# ── Config ────────────────────────────────────────────────────────────────────
TOKEN = "token" # Created token from Synoptic API
BASE_URL = "https://api.synopticdata.com/v2/stations/timeseries"

# Station ID(s) you want to pull from — comma separate multiple e.g. "STID1,STID2"
STATION_ID = "COOPICYI4"

# Date range — adjust as needed
START_DATE = "202604081521"   # YYYYmmddHHMM in UTC
END_DATE   = "202604301521"

# Variables to request
VARS = ",".join([
    "air_temp",
    "snow_depth",
    "snow_accum_24_hour",
    "precip_accum_24_hour",
    "air_temp_high_24_hour",
    "air_temp_low_24_hour"
])

# ── Pull Data ─────────────────────────────────────────────────────────────────
def pull_synoptic_data(station_id, start, end, token, vars_str):
    params = {
        "token":  token,
        "stid": "COOPICYI4",
        "start":  start,
        "end":    end,
        "vars":   vars_str,
        "units":  "english",   # change to "metric" if preferred
        "output": "json"
    }

    print(f"Requesting data for station: {station_id}")
    r = requests.get(BASE_URL, params=params, timeout=60)
    print(f"Status: {r.status_code}")
    print(f"URL: {r.url}")
    r.raise_for_status()

    data = r.json()

    # Check API response code
    summary = data.get("SUMMARY", {})
    if summary.get("RESPONSE_CODE") != 1:
        raise ValueError(f"API error: {summary.get('RESPONSE_MESSAGE')}")

    stations = data.get("STATION", [])
    if not stations:
        raise ValueError("No stations returned.")

    all_dfs = []

    for station in stations:
        stid = station["STID"]
        obs  = station["OBSERVATIONS"]

        # Build base DataFrame from timestamps
        df = pd.DataFrame({"datetime": pd.to_datetime(obs["date_time"])})

        # Map expected set_1 keys to clean column names
        var_map = {
          "air_temp_set_1":               "air_temp",
          "snow_depth_set_1":             "snow_depth",
          "snow_accum_24_hour_set_1":     "snow_accum",
          "precip_accum_24_hour_set_1":   "precip_accum",
          "air_temp_high_24_hour_set_1":  "air_temp_high",
          "air_temp_low_24_hour_set_1":   "air_temp_low"
        }

        for raw_key, clean_name in var_map.items():
            if raw_key in obs:
                df[clean_name] = obs[raw_key]
            else:
                # Try set_1d (derived variables use this suffix)
                derived_key = raw_key.replace("_set_1", "_set_1d")
                if derived_key in obs:
                    df[clean_name] = obs[derived_key]
                else:
                    print(f"  Warning: {raw_key} not found for station {stid}")
                    df[clean_name] = None

        df.insert(0, "stid", stid)
        all_dfs.append(df)

    result = pd.concat(all_dfs, ignore_index=True)
    return result


# ── Run ───────────────────────────────────────────────────────────────────────
df_weather = pull_synoptic_data(
    station_id=STATION_ID,
    start=START_DATE,
    end=END_DATE,
    token=TOKEN,
    vars_str=VARS
)

print(df_weather.head())
print(df_weather.dtypes)
print(f"\nRows returned: {len(df_weather)}")

# Optional: save to CSV
# df_weather.to_csv("synoptic_weather.csv", index=False)

# After pulling df_weather, fill missing dates with interpolation
df_weather["datetime"] = pd.to_datetime(df_weather["datetime"], utc=True)

# Create a temporary 'daily_date' column for reindexing purposes
# This ensures the original 'datetime' column remains in the DataFrame
df_weather['daily_date'] = df_weather['datetime'].dt.normalize()

# Reindex to a full daily range
all_dates = pd.date_range(
    start=df_weather["daily_date"].min(), # Use the new 'daily_date' for range
    end=df_weather["daily_date"].max(),
    freq="D",
    tz="UTC"
)

df_weather = (
    df_weather
    .set_index("daily_date") # Set the temporary daily index
    .reindex(all_dates)     # Reindex, which will introduce NaNs in 'datetime' for new dates
    .rename_axis("date")    # Rename the index to 'date'
    .reset_index()          # Convert the 'date' index back to a column named 'date'
                            # Now df_weather has 'date' (from the new index) and 'datetime' (original, with NaT for new rows)
)

# Fill stid forward so it isn't NaN
df_weather["stid"] = df_weather["stid"].ffill()

# Interpolate numeric columns
numeric_cols = ["air_temp", "snow_depth", "snow_accum",
                "precip_accum", "air_temp_high", "air_temp_low"]

# Set date as index for time-based interpolation
df_weather = df_weather.set_index("date")

df_weather[numeric_cols] = df_weather[numeric_cols].interpolate(
    method="time",
    limit=3,
    limit_direction="forward"
)

df_weather = df_weather.reset_index()

# Flag interpolated rows and fill datetime
df_weather["interpolated"] = df_weather["datetime"].isna() # 'datetime' column now exists
df_weather["datetime"] = df_weather["datetime"].fillna(df_weather["date"]) # Fill original datetime (NaT) with the daily 'date'

print(f"Filled {df_weather['interpolated'].sum()} missing days")
print(df_weather[df_weather["interpolated"]])

# ── Write to PI Tags ───────────────────────────────────────────────────────────────────────
from datetime import datetime
import os
import pandas as pd
import requests

session = requests.Session()
session.auth = ("user", "password")

BASE_URL = "https://pi-vision.facilities.uiowa.edu/piwebapi"
PI_SERVER = "\\piserver.facilities.uiowa.edu"
session.headers.update({
    "Accept": "application/json",
    "Content-Type": "application/json",
    "X-Requested-With": ""
})
def get_point_webid(tag_name):
    """
    Look up the PI WebID for a tag name.
    """
    tag_path = rf"{PI_SERVER}\{tag_name}"
    r = session.get(
        f"{BASE_URL}/points",
        params={"path": tag_path},
        timeout=60
    )
    print("\n" + "=" * 80)
    print("POINT LOOKUP")
    print(f"TAG: {tag_name}")
    print(f"PATH: {tag_path}")
    print(f"STATUS: {r.status_code}")
    print(f"FINAL URL: {r.url}")
    print(f"RESPONSE TEXT: {r.text[:1500]}")
    print("=" * 80)
    r.raise_for_status()
    return r.json()["WebId"]

def build_payload(rows, time_col, value_col):
    payload = []
    for _, row in rows.iterrows():
        ts = pd.to_datetime(row[time_col], utc=True)
        val = row[value_col]
        if pd.isna(val):
            continue
        payload.append({
            "Timestamp": ts.strftime("%Y-%m-%dT%H:%M:%SZ"),
            "Value": float(val)
        })
    return payload

def write_recorded_values(
    tag_name,
    rows,
    time_col,
    value_col,
    update_option="Replace"
):
    webid = get_point_webid(tag_name)
    payload = build_payload(rows, time_col, value_col)
    if not payload:
        print(f"No valid values to write for {tag_name}")
        return None
    write_url = f"{BASE_URL}/streams/{webid}/recorded"
    params = {
        "updateOption": update_option,
        "bufferOption": "BufferIfPossible"
    }
    print("\n" + "=" * 80)
    print("RECORDED WRITE TEST")
    print(f"TAG: {tag_name}")
    print(f"WEBID: {webid}")
    print(f"WRITE URL: {write_url}")
    print(f"PARAMS: {params}")
    print("PAYLOAD PREVIEW:")
    print(payload[:3])
    print("=" * 80)

    r = session.post(
        write_url,
        params=params,
        json=payload,
        timeout=60
    )
    print("POST STATUS:", r.status_code)
    print("FINAL URL:", r.url)
    print("RESPONSE HEADERS:", dict(r.headers))
    print("RESPONSE TEXT:", r.text[:2000])
    if not r.ok:
        print(
            "\nWrite failed. Since point lookup succeeded but POST failed, "
            "this likely indicates PI write permission, Web API write access, "
            "or point data security issue."
        )
        r.raise_for_status()
    print(f"Wrote {len(payload)} values to {tag_name}")
    return r

# ── PI Tag mapping for Synoptic weather variables ─────────────────────────────
SYNOPTIC_TAG_MAP = {
    "air_temp":     "IowaCity_Weather_SynopticDailyAirTemp",
    "snow_depth":   "IowaCity_Weather_SynopticDailySnowDepth",
    "snow_accum":   "IowaCity_Weather_SynopticDailySnowAccumulation",
    "precip_accum": "IowaCity_Weather_SynopticDailyPrecipitationAccumulation",
    "air_temp_high":"IowaCity_Weather_SynopticDailyAirTempHigh",
    "air_temp_low": "IowaCity_Weather_SynopticDailyAirTempLow",
}

# ── Write all synoptic variables to their PI tags ─────────────────────────────
def write_synoptic_to_pi(df, tag_map, time_col="date", update_option="Replace"):
    """
    Write each weather variable in df to its corresponding PI tag.
    df       : your df_weather DataFrame
    tag_map  : dict mapping df column names to PI tag names
    time_col : the datetime column to use as the PI timestamp
    """
    results = {}
    for col, tag_name in tag_map.items():
        if col not in df.columns:
            print(f"Skipping {col} — column not found in DataFrame")
            continue

        print(f"\n{'='*60}")
        print(f"Writing {col} → {tag_name}")

        r = write_recorded_values(
            tag_name=tag_name,
            rows=df,
            time_col=time_col,
            value_col=col,
            update_option=update_option
        )
        results[col] = r

    print(f"\n{'='*60}")
    print("Done. Summary:")
    for col, r in results.items():
        if r is None:
            print(f"  {col}: skipped or dry run")
        else:
            print(f"  {col}: {r.status_code}")

    return results

# ── Run ───────────────────────────────────────────────────────────────────────
results = write_synoptic_to_pi(df_weather, SYNOPTIC_TAG_MAP)